name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --clean build.spec

    - name: Create release archive
      run: |
        mkdir release
        cp dist/MapHelper.exe release/
        cp config.json.example release/config.json
        cp settings.json.example release/settings.json
        cp README.md release/
        cp LICENSE release/
        echo "# MapHelper - Standalone Executable" > release/README.txt
        echo "" >> release/README.txt
        echo "All maps and fonts are embedded in MapHelper.exe" >> release/README.txt
        echo "" >> release/README.txt
        echo "To run:" >> release/README.txt
        echo "1. Double-click MapHelper.exe" >> release/README.txt
        echo "2. Press M to toggle map overlay" >> release/README.txt
        echo "3. Press R to reset cache" >> release/README.txt
        echo "4. Press ESC twice to exit" >> release/README.txt
        echo "" >> release/README.txt
        echo "First run will ask you to select the map area (ROI)." >> release/README.txt
        echo "Settings are saved in config.json and settings.json" >> release/README.txt
        Compress-Archive -Path release/* -DestinationPath MapHelper-${{ github.ref_name }}-Windows.zip
      shell: powershell

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MapHelper-Windows
        path: MapHelper-${{ github.ref_name }}-Windows.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: MapHelper-${{ github.ref_name }}-Windows.zip
        body: |
          ## Dark and Darker Map Helper ${{ github.ref_name }}

          ### 🚀 Truly Standalone Executable
          - **Single .exe file** - All maps and fonts embedded!
          - **No installation required** - Just download and run
          - **No Python needed** - Completely self-contained

          ### 📥 Installation
          1. Download `MapHelper-${{ github.ref_name }}-Windows.zip`
          2. Extract to a folder
          3. Double-click `MapHelper.exe` - That's it!

          ### ✨ Features
          - Auto-detect map from first cell
          - Real-time overlay with location names
          - Multi-language support (EN/ZH)
          - Configurable detection parameters
          - Smart caching (15 min)

          ### 🎮 Controls
          - **M**: Toggle map overlay
          - **R**: Reset cache
          - **ESC x2**: Exit

          ### 📋 What's Included
          - `MapHelper.exe` (standalone, ~100MB with all maps embedded)
          - `config.json` (ROI settings)
          - `settings.json` (detection parameters)
          - `README.md` (full documentation)

          See README.md for troubleshooting and advanced configuration.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
